export const REGISTER_REQUEST = 'USERS_REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'USERS_REGISTER_FAILURE';

export const LOGIN_REQUEST = 'USERS_GETALL_REQUEST';
export const LOGIN_SUCCESS = 'USERS_GETALL_SUCCESS';
export const LOGIN_FAILURE = 'USERS_GETALL_FAILURE';
    
export const LOGOUT = 'USERS_LOGOUT';

export const GETALL_REQUEST = 'PRODUCTS_GETALL_REQUEST';
export const GETALL_SUCCESS = 'PRODUCTS_GETALL_SUCCESS';
export const GETALL_FAILURE = 'PRODUCTS_GETALL_FAILURE';

export const DELETE_REQUEST = 'PRODUCTS_DELETE_REQUEST';
export const DELETE_SUCCESS = 'PRODUCTS_DELETE_SUCCESS';
export const DELETE_FAILURE = 'PRODUCTS_DELETE_FAILURE';  

export const PRODUCTS_ADD_REQUEST = 'PRODUCTS_ADD_REQUEST';
export const PRODUCTS_ADD_SUCCESS = 'PRODUCTS_ADD_SUCCESS';
export const PRODUCTS_ADD_FAILURE = 'PRODUCTS_ADD_FAILURE';  

export const PRODUCTS_GETBYID_REQUEST = 'PRODUCTS_GETBYID_REQUEST';
export const PRODUCTS_GETBYID_SUCCESS = 'PRODUCTS_GETBYID_SUCCESS';
export const PRODUCTS_GETBYID_FAILURE = 'PRODUCTS_GETBYID_FAILURE';  

export const PRODUCTS_UPDATE_REQUEST = 'PRODUCTS_UPDATE_REQUEST';
export const PRODUCTS_UPDATE_SUCCESS = 'PRODUCTS_UPDATE_SUCCESS';
export const PRODUCTS_UPDATE_FAILURE = 'PRODUCTS_UPDATE_FAILURE';  